In [1]:
import pandas as pd
import numpy as np

df1 = pd.read_csv("/Users/royann/Downloads/species_clean.csv")
df2 = pd.read_csv("/Users/royann/Downloads/species_details.csv",sep=";")

In [43]:
df2

,species_id,GBIF_species_id,GBIF_species_name,GBIF_genus_name,GBIF_family_name,GBIF_kingdom_name
0,0,5356345,Laburnum anagyroides,Laburnum,Fabaceae,Plantae
1,1,2874515,Cucurbita maxima,Cucurbita,Cucurbitaceae,Plantae
2,2,2874569,Cucumis sativus,Cucumis,Cucurbitaceae,Plantae
3,3,3033363,Ranunculus acris,Ranunculus,Ranunculaceae,Plantae
4,4,3034830,Heracleum sphondylium,Heracleum,Apiaceae,Plantae
...,...,...,...,...,...,...
17032,17032,1817690,Lophocampa mixta,Lophocampa,Arctiidae,Animalia
17033,17033,6177974,Falco peregrinus,Falco,Falconidae,Animalia
17034,17034,3802360,Iochroma cyaneum,Iochroma,Solanaceae,Plantae
17035,17035,1162845,Microphotus angustus,Microphotus,Lampyridae,Animalia
17036,17036,5164882,Vella americana,Vella,Myrmeleontidae,Animalia

In [ ]:
noms_menaces = df1["scientific_name"].str.strip().str.lower()
noms_geolife = df2["GBIF_species_name"].str.strip().str.lower()

df = df2[noms_geolife.isin(noms_menaces)]

In [3]:
df

,species_id,GBIF_species_id,GBIF_species_name,GBIF_genus_name,GBIF_family_name,GBIF_kingdom_name
78,78,2874027,Cistus salviifolius,Cistus,Cistaceae,Plantae
84,84,3170115,Gentiana cruciata,Gentiana,Gentianaceae,Plantae
113,113,7331741,Melampyrum arvense,Melampyrum,Orobanchaceae,Plantae
114,114,3172358,Fraxinus excelsior,Fraxinus,Oleaceae,Plantae
147,147,3034426,Eryngium campestre,Eryngium,Apiaceae,Plantae
...,...,...,...,...,...,...
14831,14831,5286275,Targionia hypophylla,Targionia,Targioniaceae,Plantae
14910,14910,5323092,Liparis loeselii,Liparis,Orchidaceae,Plantae
16599,16599,6177943,Numenius phaeopus,Numenius,Scolopacidae,Animalia
16768,16768,7193945,Phoca vitulina,Phoca,Phocidae,Animalia
17033,17033,6177974,Falco peregrinus,Falco,Falconidae,Animalia

In [49]:
df.to_csv('menacee.csv',index=False)